export const KeepContact={
    AUTH:{
        EVENT_DETAILS: 'EVENT_DETAILS',
        USER_SET_SELF: 'USER_SET_SELF',
        SET_GRAPHIC_SETTINGS: 'SET_GRAPHIC_SETTINGS',
        EVENT_ROLE_LABLES: 'EVENT_ROLE_LABLES',
        SET_LANG : 'SET_LANG',
        APP_SETTINGS: "USER_META_DATA",
        SET_USER_META_DATA : "SET_USER_META_DATA"
    },
    EVENT: {
        ADD_EVENT: "ADD_EVENT",
        IS_EVENT_FORM_UPDATED: "IS_EVENT_FORM_UPDATED",
        CURRENT_EVENT_UUID: "CURRENT_EVENT_UUID",
        UPDATE_TEMP_REC_DATA: "UPDATE_TEMP_REC_DATA",
        UPDATE_CURRENT_EVENT: "UPDATE_CURRENT_EVENT",
        PUBLISH_EVENT_SUBMIT: "PUBLISH_EVENT_SUBMIT",
        SAVE_EVENT_SUBMIT: "SAVE_EVENT_SUBMIT",
        UPDATE_SPACE_FORM_STATUS: "UPDATE_SPACE_FORM_STATUS",
        UPDATE_USER_POP_UP:"UPDATE_USER_POP_UP",
        UPDATE_USER_SORT_MODEL:"UPDATE_USER_SORT_MODEL",
        UPDATE_ALL_DAY_EVENT:"UPDATE_ALL_DAY_EVENT",
    },
    GROUP: {
        UPDATE_CURRENT_GROUP: "UPDATE_CURRENT_GROUP",
        UPDATE_ORGANISATION_NAME: "UPDATE_ORGANISATION_NAME",
        UPDATE_ENGAGEMENT_TAB_DATA:{
            DATE_DROPDOWN_VAL:"DATE_DROPDOWN_VAL",
            RANGE_PICKER_VALUE : "RANGE_PICKER_VALUE",
        },
        UPDATE_ANALYTIC_GRP_DROPDOWN:"UPDATE_ANALYTIC_GRP_DROPDOWN",
        UPDATE_SEARCHED_KEY:"UPDATE_SEARCHED_KEY",
        UPDATE_ALL_DAY_EVENT_ENABLED:"UPDATE_ALL_DAY_EVENT_ENABLED",
        ANALYTICS_RANGE_PICKER_VALUE:"ANALYTICS_RANGE_PICKER_VALUE",
        ANALYTICS_DROPDOWN_DATA:"ANALYTICS_DROPDOWN_DATA",
    },
    ANALYTICS: {
        UPDATE_RECURRENCES_LIST: 'UPDATE_RECURRENCES_LIST',
        UPDATE_ANALYTICS_LIST: 'UPDATE_ANALYTICS_LIST',
        DATE_DROPDOWN_VAL:"DATE_DROPDOWN_VAL",
        FILTER_ANALYTICS_LIST: 'FILTER_ANALYTICS_LIST',
        SET_PAGE_REFRESH: 'SET_PAGE_REFRESH',


    }
}