<?php

namespace Modules\Messenger\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;

/**
 * Class ChannelForPersonalMessageRequest
 * @package Modules\Messenger\Http\Requests
 *
 * For conversation open
 */
class ChannelForPersonalMessageRequest extends FormRequest {
    /**
     * @return array
     */
    public function rules() {
        return [
            'user_id' => 'required|exists:tenant.users,id',
        ];
    }
    
    /**
     * @return bool
     */
    public function authorize() {
        return TRUE;
    }
    
    protected function failedValidation(Validator $validator) {
        throw new HttpResponseException(response()->json([
            'status' => FALSE,
            'msg'    => implode(',', $validator->errors()->all())
        ],422));
//        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
    
}
