<?php

namespace Modules\Messenger\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;
use Illuminate\Validation\Rule;
use Modules\Messenger\Rules\NoSpecialCharRule;
class CreateChannelRequest extends FormRequest {
    
    public function rules() {
        return [
            'channel_name' => [
                'required',
                'string',
                new NoSpecialCharRule,
                'max:' . config('messenger.validations.channel_name'),
                Rule::unique('tenant.im_channels', 'channel_name')->whereNull('deleted_at'),
            ],
            'is_private'   => 'required|in:0,1',
        ];
    }
    
    public function authorize() {
        return TRUE;
    }
    
    protected function failedValidation(Validator $validator) {
        throw new HttpResponseException(response()->json([
            'status' => FALSE,
            'msg'    => implode(',', $validator->errors()->all())
        ],422));
//        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
    
}
