<?php

namespace Modules\Messenger\Http\Requests;

use App\Workshop;
use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\Rule;
use Modules\Messenger\Entities\Channel;
use Modules\Messenger\Entities\ChannelUser;
use Modules\Messenger\Entities\UserChannelUserRelation;
use Modules\Messenger\Entities\WorkshopTopic;
use Modules\Messenger\Service\AuthorizationService;
use Modules\Messenger\Service\ChannelService;

class MessageReactionRequest extends FormRequest {
    /**
     * @return array
     */
    public function rules() {
        return [
            'message_id'    => [
                'required',
                Rule::exists('tenant.im_messages', 'id')->whereNull('deleted_at')
            ],
            'reaction_type' => 'required|in:1,2',
            'channel_uuid'  => [
                'required',
                Rule::exists('tenant.im_channels', 'uuid')->whereNull('deleted_at'),
                Rule::exists('tenant.im_messages', 'channel_uuid')->where('id', $this->message_id),
            ]
        ];
    }
    
    /**
     * @return bool
     */
    public function authorize() {
        return AuthorizationService::getInstance()->isUserBelongsToChannel($this->channel_uuid, Auth::user());
    }
    
    protected function failedValidation(Validator $validator) {
        throw new HttpResponseException(response()->json([
            'status' => FALSE,
            'msg'    => implode(',', $validator->errors()->all())
        ],422));
//        parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
    
}
