/**
 * @module
 */

/**
 * ---------------------------------------------------------------------------------------------------------------------
 * @description Here all the reducer actions name are listed which are handled in respective reducer files
 * ---------------------------------------------------------------------------------------------------------------------
 *
 * @type {Object}
 * @property {Object} AUTH Auth related redux keys
 * @property {String} AUTH.EVENT_DETAILS key value for EVENT_DETAILS
 * @property {Object} EVENT EVENT related redux keys
 * @property {String} EVENT.SET_EVENT_GRAPHICS SET_EVENT_GRAPHICS redux key value
 * @property {String} EVENT.GET_SPACES GET_SPACES redux key value
 * @property {String} EVENT.SET_EVENT_SPACES SET_EVENT_SPACES redux key value
 * @property {String} EVENT.ADD_EVENT_MEMBER_SINGLE ADD_EVENT_MEMBER_SINGLE redux key value
 * @property {String} EVENT.ADD_EVENT_MEMBER_CONVERSATION ADD_EVENT_MEMBER_CONVERSATION redux key value
 * @property {String} EVENT.CHANGE_SPACE CHANGE_SPACE redux key value
 * @property {String} EVENT.CHANGE_CONVERSATION_ID CHANGE_CONVERSATION_ID redux key value
 * @property {String} EVENT.DELETE_CONVERSATION DELETE_CONVERSATION redux key value
 * @property {String} EVENT.FILTER_ONLINE_MEMBER FILTER_ONLINE_MEMBER redux key value
 * @property {String} EVENT.ADD_EVENT_MEMBER_BY_USER_ID ADD_EVENT_MEMBER_BY_USER_ID redux key value
 * @property {String} EVENT.UPDATE_USER_CONVERSATION UPDATE_USER_CONVERSATION redux key value
 * @property {String} EVENT.ADD_NEW_EVENT_MEMBER ADD_NEW_EVENT_MEMBER redux key value
 * @property {String} EVENT.UPDATE_EVENT_CONVERSATION UPDATE_EVENT_CONVERSATION redux key value
 * @property {String} EVENT.SET_EVENT_URL SET_EVENT_URL redux key value
 * @property {String} EVENT.TOGGLE_DND TOGGLE_DND redux key value
 * @property {String} EVENT.ADD_USER_TO_ACTIVE_CONVERSATION ADD_USER_TO_ACTIVE_CONVERSATION redux key value
 * @property {String} EVENT.UPDATE_INIT_DATA UPDATE_INIT_DATA redux key value
 * @property {String} EVENT.UPDATE_INIT_NAME UPDATE_INIT_NAME redux key value
 * @property {String} EVENT.UPDATE_SPACE_USERS_COUNT UPDATE_SPACE_USERS_COUNT redux key value
 * @property {String} EVENT.CHANGE_MEDIA_DEVICES CHANGE_MEDIA_DEVICES redux key value
 * @property {String} EVENT.CHANGE_ONLINE_USERS_IDENTIFIER CHANGE_ONLINE_USERS_IDENTIFIER redux key value
 * @property {Object} NEW_INTERFACE NEW_INTERFACE related redux keys
 * @property {String} NEW_INTERFACE.SET_SINGLE_USER_DATA SET_SINGLE_USER_DATA Key value
 * @property {String} NEW_INTERFACE.UPDATE_VIDEO_MUTE_TEXT UPDATE_VIDEO_MUTE_TEXT Key value
 * @property {String} NEW_INTERFACE.SET_VISIBILITY_DATA SET_VISIBILITY_DATA Key value
 * @property {String} NEW_INTERFACE.ADD_EVENT_MEMBERS_SINGLE ADD_EVENT_MEMBERS_SINGLE Key value
 * @property {String} NEW_INTERFACE.ADD_EVENT_MEMBER_CONVERSATIONS ADD_EVENT_MEMBER_CONVERSATIONS Key value
 * @property {String} NEW_INTERFACE.CHANGE_MEDIA_DEVICE CHANGE_MEDIA_DEVICE Key value
 * @property {String} NEW_INTERFACE.ADD_USER_TO_ACTIVE_CONVERSATIONS ADD_USER_TO_ACTIVE_CONVERSATIONS Key value
 * @property {String} NEW_INTERFACE.UPDATE_EVENT_CONVERSATIONS UPDATE_EVENT_CONVERSATIONS Key value
 * @property {String} NEW_INTERFACE.SET_GRAPHICS SET_GRAPHICS Key value
 * @property {String} NEW_INTERFACE.UPDATE_CONVERSATION_PROFILE UPDATE_CONVERSATION_PROFILE Key value
 * @property {String} NEW_INTERFACE.SET_CALLED_USER_ID SET_CALLED_USER_ID Key value
 * @property {String} NEW_INTERFACE.ZOOM_USER_ADMIT ZOOM_USER_ADMIT Key value
 * @property {String} NEW_INTERFACE.UPDATE_TEST_AUDIO_URL UPDATE_TEST_AUDIO_URL Key value
 * @property {String} NEW_INTERFACE.SET_BADGE SET_BADGE Key value
 * @property {String} NEW_INTERFACE.SET_SPACE_HOST_DATA SET_SPACE_HOST_DATA Key value
 * @property {String} NEW_INTERFACE.UPDATE_CONVERSATION_TYPE UPDATE_CONVERSATION_TYPE Key value
 * @property {String} NEW_INTERFACE.SORT_SPACES SORT_SPACES Key value
 * @property {String} NEW_INTERFACE.ADD_EVENT_MEMBER_BY_USER_IDS ADD_EVENT_MEMBER_BY_USER_IDS Key value
 * @property {String} NEW_INTERFACE.RESET_SPACE RESET_SPACE Key value
 * @property {String} NEW_INTERFACE.SET_USER_INFO_DATA SET_USER_INFO_DATA Key value
 * @property {String} NEW_INTERFACE.CONTENT_MANAGE_DATA CONTENT_MANAGE_DATA Key value
 * @property {String} NEW_INTERFACE.VIDEO_PLAYER_STARTED VIDEO_PLAYER_STARTED Key value
 * @property {String} NEW_INTERFACE.FILTER_ONLINE_MEMBERS FILTER_ONLINE_MEMBERS Key value
 * @property {String} NEW_INTERFACE.CONFERENCE_UPDATE CONFERENCE_UPDATE Key value
 * @property {String} NEW_INTERFACE.SET_EVENT_DATA SET_EVENT_DATA Key value
 * @property {String} NEW_INTERFACE.UPDATE_USERS_CONVERSATION UPDATE_USERS_CONVERSATION Key value
 * @property {String} NEW_INTERFACE.PRIVATE_CONVERSATION PRIVATE_CONVERSATION Key value
 * @property {String} NEW_INTERFACE.UPDATE_SPACE_USERS_COUNTS UPDATE_SPACE_USERS_COUNTS Key value
 * @property {String} NEW_INTERFACE.SET_CALL_STATUS SET_CALL_STATUS Key value
 * @property {String} NEW_INTERFACE.SET_USER_AUTH SET_USER_AUTH Key value
 * @property {String} NEW_INTERFACE.CHANGE_SPACES CHANGE_SPACES Key value
 * @property {String} NEW_INTERFACE.GRID_VISIBILITY_UPDATE GRID_VISIBILITY_UPDATE Key value
 * @property {String} NEW_INTERFACE.CONTENT_COMPONENT_VISIBILITY CONTENT_COMPONENT_VISIBILITY Key value
 * @property {String} NEW_INTERFACE.CONV_FULL_SCREEN CONV_FULL_SCREEN Key value
 * @property {String} NEW_INTERFACE.SET_MAIN_HOST SET_MAIN_HOST Key value
 * @property {String} NEW_INTERFACE.HANDLE_PRIVATE_CONVERSATION HANDLE_PRIVATE_CONVERSATION Key value
 * @property {String} NEW_INTERFACE.SET_SPACES_DATA SET_SPACES_DATA Key value
 * @property {String} NEW_INTERFACE.DELETE_CONVERSATIONS DELETE_CONVERSATIONS Key value
 * @property {String} NEW_INTERFACE.CONVERSATION_MUTE_UPDATE CONVERSATION_MUTE_UPDATE Key value
 * @property {String} NEW_INTERFACE.CONTENT_MUTE_UPDATE CONTENT_MUTE_UPDATE Key value
 * @property {String} NEW_INTERFACE.PAGINATION_UPDATE PAGINATION_UPDATE Key value
 * @property {String} NEW_INTERFACE.ZOOM_INITIALIZE_UPDATE ZOOM_INITIALIZE_UPDATE Key value
 * @property {String} NEW_INTERFACE.ADD_NEW_EVENT_MEMBERS ADD_NEW_EVENT_MEMBERS Key value
 * @property {String} NEW_INTERFACE.CHANGE_CONVERSATION_IDS CHANGE_CONVERSATION_IDS Key value
 * @property {String} NEW_INTERFACE.ASK_TO_JOIN ASK_TO_JOIN Key value
 * @property {String} NEW_INTERFACE.SET_TAGS SET_TAGS Key value
 *
 */

export const KeepContact = {
    AUTH: {
        EVENT_DETAILS: 'EVENT_DETAILS'
    },
    EVENT: {

        SET_EVENT_GRAPHICS: 'SET_EVENT_GRAPHICS',
        GET_SPACES: 'GET_SPACES',
        SET_EVENT_SPACES: 'SET_EVENT_SPACES',
        ADD_EVENT_MEMBER_SINGLE: 'ADD_EVENT_MEMBER_SINGLE',
        ADD_EVENT_MEMBER_CONVERSATION: 'ADD_EVENT_MEMBER_CONVERSATION',
        CHANGE_SPACE: 'CHANGE_SPACE',
        CHANGE_CONVERSATION_ID: 'CHANGE_CONVERSATION_ID',
        DELETE_CONVERSATION: 'DELETE_CONVERSATION',
        FILTER_ONLINE_MEMBER: 'FILTER_ONLINE_MEMBER',
        ADD_EVENT_MEMBER_BY_USER_ID: 'ADD_EVENT_MEMBER_BY_USER_ID',
        UPDATE_USER_CONVERSATION: 'UPDATE_USER_CONVERSATION',
        ADD_NEW_EVENT_MEMBER: 'ADD_NEW_EVENT_MEMBER',
        UPDATE_EVENT_CONVERSATION: 'UPDATE_EVENT_CONVERSATION',
        SET_EVENT_URL: 'SET_EVENT_URL',
        TOGGLE_DND: 'TOGGLE_DND',
        ADD_USER_TO_ACTIVE_CONVERSATION: "ADD_USER_TO_ACTIVE_CONVERSATION",
        UPDATE_INIT_DATA: 'UPDATE_INIT_DATA',
        UPDATE_INIT_NAME: 'UPDATE_INIT_NAME',
        UPDATE_SPACE_USERS_COUNT: 'UPDATE_SPACE_USERS_COUNT',
        CHANGE_MEDIA_DEVICES: "CHANGE_MEDIA_DEVICES",
        CHANGE_ONLINE_USERS_IDENTIFIER: "CHANGE_ONLINE_USERS_IDENTIFIER",
        SET_EVENT_DESIGN_SETTINGS: "SET_EVENT_DESIGN_SETTINGS",
        SET_EVENT_GROUP_LOGO: "SET_EVENT_GROUP_LOGO",

    },
    NEW_INTERFACE: {
        SET_BADGE: 'SET_BADGE',
        SET_TAGS: 'SET_TAGS',
        SET_GRAPHICS: 'SET_GRAPHICS',
        SET_EVENT_DATA: 'SET_EVENT_DATA',
        SET_SPACES_DATA: 'SET_SPACES_DATA',
        SET_VISIBILITY_DATA: 'SET_VISIBILITY_DATA',
        UPDATE_CONVERSATION_PROFILE: 'UPDATE_CONVERSATION_PROFILE',
        FILTER_ONLINE_MEMBERS: 'FILTER_ONLINE_MEMBERS',
        UPDATE_USERS_CONVERSATION: 'UPDATE_USERS_CONVERSATION',
        UPDATE_EVENT_CONVERSATIONS: 'UPDATE_EVENT_CONVERSATIONS',
        UPDATE_CONVERSATION_OTHER_MUTE: 'UPDATE_CONVERSATION_OTHER_MUTE',
        DELETE_CONVERSATIONS: 'DELETE_CONVERSATIONS',
        ADD_USER_TO_ACTIVE_CONVERSATIONS: 'ADD_USER_TO_ACTIVE_CONVERSATIONS',
        CHANGE_MEDIA_DEVICE: 'CHANGE_MEDIA_DEVICE',
        ADD_EVENT_MEMBERS_SINGLE: 'ADD_EVENT_MEMBERS_SINGLE',
        ADD_EVENT_MEMBER_CONVERSATIONS: 'ADD_EVENT_MEMBER_CONVERSATIONS',
        ADD_NEW_EVENT_MEMBERS: 'ADD_NEW_EVENT_MEMBERS',
        CHANGE_CONVERSATION_IDS: 'CHANGE_CONVERSATION_IDS',
        SET_USER_AUTH: 'SET_USER_AUTH',
        UPDATE_SPACE_USERS_COUNTS: 'UPDATE_SPACE_USERS_COUNTS',
        ADD_EVENT_MEMBER_BY_USER_IDS: 'ADD_EVENT_MEMBER_BY_USER_IDS',
        SORT_SPACES: 'SORT_SPACES',
        CHANGE_SPACES: 'CHANGE_SPACES',
        RESET_SPACE: 'RESET_SPACE',
        ASK_TO_JOIN: 'ASK_TO_JOIN',
        SET_CALL_STATUS: 'SET_CALL_STATUS',

        SET_SPACE_HOST_DATA: 'SET_SPACE_HOST_DATA',//SPACEHOST
        SET_MAIN_HOST: 'SET_MAIN_HOST',
        SET_USER_INFO_DATA: 'SET_USER_INFO_DATA',
        SET_SINGLE_USER_DATA: 'SET_SINGLE_USER_DATA',
        PRIVATE_CONVERSATION: 'PRIVATE_CONVERSATION',
        SET_CALLED_USER_ID: 'CALLED_USER_ID',
        UPDATE_CONVERSATION_TYPE: 'UPDATE_CONVERSATION_TYPE',
        HANDLE_PRIVATE_CONVERSATION: 'HANDLE_PRIVATE_CONVERSATION',
        CONFERENCE_UPDATE: 'CONFERENCE_UPDATE',
        PAGINATION_UPDATE: 'PAGINATION_UPDATE',

        //    ZOOM ACTIONS
        ZOOM_INITIALIZE_UPDATE: 'ZOOM_INITIALIZE_UPDATE',

        // CONVERSATION META STATE
        CONVERSATION_MUTE_UPDATE: 'CONVERSATION_META_UPDATE',
        CONV_FULL_SCREEN: 'CONVERSATION_FULL_SCREEN_UPDATE',

        // GRID META
        GRID_VISIBILITY_UPDATE: 'GRID_VISIBILITY_UPDATE',

        // CONTENT META
        CONTENT_MANAGE_DATA: 'CONTENT_MANAGE_DATA',
        CONTENT_COMPONENT_VISIBILITY: 'CONTENT_COMPONENT_VISIBILITY',
        CONTENT_MUTE_UPDATE: 'CONTENT_MUTE_UPDATE',
        ZOOM_USER_ADMIT: 'ZOOM_USER_ADMIT',
        VIDEO_PLAYER_STARTED: 'VIDEO_PLAYER_STARTED',
        UPDATE_VIDEO_MUTE_TEXT: 'UPDATE_VIDEO_MUTE_TEXT',

        UPDATE_TEST_AUDIO_URL: 'UPDATE_TEST_AUDIO_URL',
        SELECTED_BG_OPTION:"SELECTED_BG_OPTION",
        PRERECORED_VOLUME: 'PRERECORED_VOLUME',
        CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

        UPDATE_SPACES_DATA: 'UPDATE_SPACES_DATA',
    },

    GRAPHICS: {
        UPDATE_APPLICATION_GRAPHICS: 'UPDATE_APPLICATION_GRAPHICS',
        UPDATE_EVENT_GRAPHICS: 'UPDATE_EVENT_GRAPHICS',
        UPDATE_EVENT_SCENERY: 'UPDATE_EVENT_SCENERY',
    },
    DASHBOARD: {
        UPDATE_NETWORKING_ALLOW: 'UPDATE_NETWORKING_ALLOW',
    }
}
export const LOADING = 'LOADING'